version: '3'

services:
  db:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Phukao98765
      - POSTGRES_DB=simple_bank